70a8a0f07107
 INFO - ::group::Log message source details
*** Found local files:
***   * /usr/local/airflow/logs/dag_id=nyc_taxi_etl/run_id=scheduled__2025-03-01T00:00:00+00:00/task_id=load_data/attempt=1.log
 INFO - ::endgroup::
[2025-03-02T07:46:43.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T07:46:43.162+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl.load_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T07:46:43.166+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl.load_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T07:46:43.166+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-02T07:46:43.172+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-01 00:00:00+00:00
[2025-03-02T07:46:43.177+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nyc_taxi_etl', 'load_data', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmp29l0oi5h']
[2025-03-02T07:46:43.179+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask load_data
[2025-03-02T07:46:43.179+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=551) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-02T07:46:43.179+0000] {standard_task_runner.py:72} INFO - Started process 552 to run task
[2025-03-02T07:46:43.224+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_taxi_etl.load_data scheduled__2025-03-01T00:00:00+00:00 [running]> on host 70a8a0f07107
[2025-03-02T07:46:43.265+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T00:00:00+00:00'
[2025-03-02T07:46:43.265+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T08:12:25.897+0000] {logging_mixin.py:190} INFO - âœ… Data successfully loaded into PostgreSQL.
[2025-03-02T08:12:25.910+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T08:12:25.963+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T08:12:25.965+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_etl, task_id=load_data, run_id=scheduled__2025-03-01T00:00:00+00:00, execution_date=20250301T000000, start_date=20250302T074643, end_date=20250302T081225
[2025-03-02T08:12:26.040+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T08:12:26.084+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T08:12:26.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
